// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P052_CodeFirstSqliteDb.Infrastructure.Database;

#nullable disable

namespace P052_CodeFirstSqliteDb.Infrastructure.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20220914161732_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("P052_CodeFirstSqliteDb.Domain.Models.Person", b =>
            {
                b.Property<int>("PersonId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("Age")
                    .HasColumnType("INTEGER");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("PersonId");

                b.ToTable("Persons");
            });
#pragma warning restore 612, 618
        }
    }
}
