// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PressentConnection.Data;

#nullable disable

namespace PressentC.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20230102155119_Nuline")]
    partial class Nuline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("PressentConnection.Program+Email", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("alternative")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tenantobjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("email");

                    b.HasIndex("tenantobjectId");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("PressentConnection.Program+Root", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("partitionKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Roots");
                });

            modelBuilder.Entity("PressentConnection.Program+Tenant", b =>
                {
                    b.Property<string>("objectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rootid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tenant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("userPrincipalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("objectId");

                    b.HasIndex("Rootid");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("PressentConnection.Project", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PressentConnection.Program+Email", b =>
                {
                    b.HasOne("PressentConnection.Program+Tenant", "tenant")
                        .WithMany("emails")
                        .HasForeignKey("tenantobjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tenant");
                });

            modelBuilder.Entity("PressentConnection.Program+Tenant", b =>
                {
                    b.HasOne("PressentConnection.Program+Root", "Root")
                        .WithMany("tenants")
                        .HasForeignKey("Rootid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Root");
                });

            modelBuilder.Entity("PressentConnection.Program+Root", b =>
                {
                    b.Navigation("tenants");
                });

            modelBuilder.Entity("PressentConnection.Program+Tenant", b =>
                {
                    b.Navigation("emails");
                });
#pragma warning restore 612, 618
        }
    }
}
