// <auto-generated />
using L05_Tasks_MSSQL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(KnygynasContext))]
    [Migration("20221130142021_PatiPirma")]
    partial class PatiPirma
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("L05_Tasks_MSSQL.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ECoverType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Several authors",
                            ECoverType = "Paperback",
                            PublishYear = 1,
                            Title = "The Bible"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Mao Zedong",
                            ECoverType = "Hardcover",
                            PublishYear = 1964,
                            Title = "Quotations from Chairman Mao Tse-Tung"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Several authors",
                            ECoverType = "Hardcover",
                            PublishYear = 700,
                            Title = "The Quran"
                        },
                        new
                        {
                            Id = 4,
                            Author = "John Tolkien",
                            ECoverType = "Hardcover",
                            PublishYear = 1954,
                            Title = "The Lord Of The Rings"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Antoine de Saint-Exupery",
                            ECoverType = "Electronic",
                            PublishYear = 1943,
                            Title = "Le Petit Prince"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Joanne Rowling",
                            ECoverType = "Paperback",
                            PublishYear = 1997,
                            Title = "Harry Potter and the Philosopher’s Stone"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Robert Baden-Powell",
                            ECoverType = "Paperback",
                            PublishYear = 1908,
                            Title = "Scouting for Boys"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Agatha Christie",
                            ECoverType = "Paperback",
                            PublishYear = 1939,
                            Title = "And Then There Were None"
                        },
                        new
                        {
                            Id = 9,
                            Author = "John Tolkien ",
                            ECoverType = "Hardcover",
                            PublishYear = 1937,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Cao Xueqin",
                            ECoverType = "Paperback",
                            PublishYear = 1791,
                            Title = "The Dream Of The Red Chambe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
